export default {
	previewStockReport: async (stockData) => {
		try {
			if (!stockData || stockData.length === 0) throw new Error("No stock data available to export.");

			// --- 1. LIBRARY SETUP ---
			if (typeof jspdf === "undefined") throw new Error("jspdf library not loaded.");
			const jsPDFConstructor = jspdf.jsPDF || jspdf;
			const doc = new jsPDFConstructor('l', 'pt', 'a4'); // Landscape is better for wide stock reports

			if (typeof doc.autoTable !== "function" && jspdf.plugin && jspdf.plugin.autotable) {
				jsPDFConstructor.API.autoTable = jspdf.plugin.autotable;
			}

			const brand = Global_Assets.getSummary();
			const margin = 15;
			const pageWidth = doc.internal.pageSize.width;

			// --- HELPER: DRAW HEADER ---
			const drawMainHeader = (currentPage, totalPages) => {
				const headerY = margin;
				try {
					const logo = Global_Assets.getLogo();
					if (logo.startsWith("data:image/")) {
						doc.addImage(logo, 'PNG', margin, headerY, 80, 25);
					}
				} catch(e) {}

				doc.setTextColor(0, 0, 0);
				doc.setFont("helvetica", "bold");
				doc.setFontSize(14);
				doc.text("INVENTORY STATUS & VALUATION REPORT", pageWidth / 2, headerY + 12, { align: "center" });
				
				doc.setFontSize(9);
				doc.setFont("helvetica", "normal");
				doc.text(`${brand.regt_name} | GST: ${brand.gst}`, pageWidth / 2, headerY + 25, { align: "center" });

				// Info Boxes
				const boxY = headerY + 40;
				const boxWidth = (pageWidth - (margin * 2) - 10) / 2;
				
				// Left Box: Report Details
				doc.rect(margin, boxY, boxWidth, 40);
				doc.setFont("helvetica", "bold");
				doc.text("Report Date:", margin + 5, boxY + 15);
				doc.text("Generated By:", margin + 5, boxY + 30);
				doc.setFont("helvetica", "normal");
				doc.text(moment().format("DD MMM YYYY, hh:mm A"), margin + 70, boxY + 15);
				doc.text("System Generated", margin + 70, boxY + 30);

				// Right Box: Page Details
				doc.rect(margin + boxWidth + 10, boxY, boxWidth, 40);
				doc.setFont("helvetica", "bold");
				doc.text("Page:", margin + boxWidth + 15, boxY + 15);
				doc.text("Status:", margin + boxWidth + 15, boxY + 30);
				doc.setFont("helvetica", "normal");
				doc.text(`${currentPage} of ${totalPages}`, margin + boxWidth + 60, boxY + 15);
				doc.text("Live Inventory Data", margin + boxWidth + 60, boxY + 30);

				return boxY + 40;
			};

			// --- 2. GENERATE TABLE ---
			doc.autoTable({
				startY: 100,
				margin: { left: margin, right: margin, top: 100 },
				head: [["S.N", "ITEM NAME", "CODE", "BRAND", "CATEGORY", "MRP", "QTY", "UOM", "COST", "TOTAL VALUE", "LAST SOLD"]],
				body: stockData.map((row, index) => [
					index + 1,
					row.product_name,
					row.product_code,
					row.brand_name,
					row.category_name,
					Number(row.mrp).toFixed(2),
					row.current_stock,
					row.uom,
					Number(row.purchase_rate).toFixed(2),
					(Number(row.current_stock) * Number(row.purchase_rate)).toFixed(2),
					row.last_sold_date ? moment(row.last_sold_date).format("DD/MM/YY") : "N/A"
				]),
				didDrawPage: (data) => {
					drawMainHeader(data.pageNumber, doc.internal.getNumberOfPages());
				},
				theme: 'grid',
				styles: { fontSize: 8, cellPadding: 3, textColor: [0, 0, 0], lineColor: [200, 200, 200] },
				headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
				columnStyles: {
					0: { cellWidth: 25 },
					1: { cellWidth: 'auto' },
					6: { halign: 'right', fontStyle: 'bold' },
					9: { halign: 'right', fontStyle: 'bold' }
				}
			});

			// --- 3. SUMMARY FOOTER ---
			const finalY = doc.lastAutoTable.finalY + 20;
			const totalVal = stockData.reduce((sum, r) => sum + (Number(r.current_stock) * Number(r.purchase_rate)), 0);
			const totalQty = stockData.reduce((sum, r) => sum + Number(r.current_stock), 0);

			doc.setFont("helvetica", "bold");
			doc.setFontSize(10);
			doc.text(`Total Items in Stock: ${totalQty}`, margin, finalY);
			doc.text(`Total Inventory Valuation: INR ${totalVal.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, margin, finalY + 15);

			// --- 4. DOWNLOAD ---
			const fileName = `Stock_Report_${moment().format("DD_MM_YY")}.pdf`;
			download(doc.output('dataurlstring'), fileName, "application/pdf");
			showAlert("Stock Report Exported Successfully", "success");

		} catch (error) {
			showAlert("Export Error: " + error.message, "error");
		}
	}
}